inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
  
Style/YodaCondition:
  Enabled: false
